In [1]:
a = [1,2,3]

In [3]:
import numpy as np

In [3]:
np.array(a)

array([1, 2, 3])

In [4]:
b = [[1,2,3],[4,5,6],[7,8,9]]

In [5]:
np.array(b)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [12]:
np.linspace(1,5,9)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [13]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
np.random.rand(4,5)

array([[0.9899062 , 0.89162654, 0.49881793, 0.03527873, 0.72663142],
       [0.02352248, 0.24795732, 0.53801942, 0.80323949, 0.20633622],
       [0.65309704, 0.39168881, 0.33291446, 0.34764768, 0.24689551],
       [0.29274201, 0.06172455, 0.60481959, 0.17670153, 0.52484521]])

In [15]:
np.random.randn(5,3)

array([[-3.82465158e-01, -1.74067512e-03, -3.13802076e-01],
       [-2.53671665e+00, -1.42255911e+00,  7.63453234e-01],
       [-8.14398516e-01,  7.77738820e-02,  5.94100002e-01],
       [-1.49354368e+00, -6.68006892e-02,  1.23572140e+00],
       [ 4.06506887e-02,  3.25139598e-01, -4.72200036e-01]])

In [16]:
np.random.randint(1,100,10)

array([60, 77,  5, 69,  5, 18, 87, 19,  2, 19])

In [21]:
arr = np.arange(25)

In [4]:
ranarr = np.random.randint(0,100,10)

In [22]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [5]:
ranarr.max()

90

In [6]:
ranarr.argmax()

5

In [7]:
ranarr

array([70, 19, 14, 27,  8, 90, 56, 33, 51, 40])

In [31]:
arr = arr.reshape(5,5)

In [33]:
arr.shape

(5, 5)

In [36]:
arr.dtype

dtype('int32')

In [37]:
arr= np.arange(0,11)

In [38]:
arr[5]

5

In [39]:
arr[2:6]

array([2, 3, 4, 5])

In [40]:
arr[:2] = 20

In [41]:
arr

array([20, 20,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
arr = np.arange(0,11)

In [44]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
arr_new = arr[:2]

In [54]:
arr_new[:] = 50

In [55]:
arr_new

array([50, 50])

In [56]:
arr

array([50, 50,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
arr_new = arr.copy()

In [58]:
arr_new

array([50, 50,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
arr_new[:6] = 999999

In [60]:
arr_new

array([999999, 999999, 999999, 999999, 999999, 999999,      6,      7,
            8,      9,     10])

In [61]:
arr

array([50, 50,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [66]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [67]:
arr_2d[0][2]

15

In [68]:
arr_2d[0,2]

15

In [75]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [80]:
arr_2d[1:,2:]

array([[30],
       [45]])

In [82]:
arr = np.arange(0,11)

In [83]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [84]:
arr < 6

array([ True,  True,  True,  True,  True,  True, False, False, False,
       False, False])

In [85]:
bool_arr = arr < 6

In [86]:
bool_arr

array([ True,  True,  True,  True,  True,  True, False, False, False,
       False, False])

In [87]:
arr[bool_arr]

array([0, 1, 2, 3, 4, 5])

In [88]:
arr[arr>6]

array([ 7,  8,  9, 10])

In [89]:
arr[arr<3]

array([0, 1, 2])

In [90]:
arr = np.arange(0,50).reshape(5,10)

In [91]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [92]:
arr[1:3, 3:5]

array([[13, 14],
       [23, 24]])

In [9]:
arr = np.arange(0,15)

In [10]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [12]:
arr * 5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70])

In [13]:
arr / arr

C:\Users\Abhijeet\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.])

In [14]:
1 / 0

ZeroDivisionError: division by zero

In [15]:
1 / arr

C:\Users\Abhijeet\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857])

In [16]:
arr / 0

C:\Users\Abhijeet\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\Abhijeet\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf])

In [17]:
arr ** 3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000,
       1331, 1728, 2197, 2744], dtype=int32)

In [18]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739])

In [19]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06])

In [20]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153,  0.0044257 ,  0.84385396,  0.90744678,  0.13673722])

In [21]:
np.log(arr)

C:\Users\Abhijeet\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733])